---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: <CLUSTER_NAME>-kubescape-operator-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '100'
spec:
  project: default
  source:
    repoURL: <GITOPS_REPO_URL>
    path: <REGISTRY_PATH>/components/kubescape-operator
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: kubescape-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
