---
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: wasmtime-spin-v2
  annotations:
    argocd.argoproj.io/sync-wave: '40'
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
handler: spin
