---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: <CLUSTER_NAME>-spinkube-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '60'
    kubefirst.konstruct.io/application-name: spinkube-operator
    kubefirst.konstruct.io/source: catalog-templates
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: spin-operator
    name: <CLUSTER_DESTINATION>
  project: <PROJECT>
  source:
    chart: spin-operator
    repoURL: ghcr.io/spinkube/charts
    targetRevision: 0.3.0
    helm:
      releaseName: spin-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
