---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '20'
  name: opencost
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: opencost
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: opencost
    repoURL: https://opencost.github.io/opencost-helm-chart
    targetRevision: 1.15.0
    helm:
      releaseName: opencost
      # values: |
      #   example: value
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
