---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: <CLUSTER_NAME>-opencost
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '20'
    kubefirst.konstruct.io/application-name: opencost
    kubefirst.konstruct.io/source: catalog-templates
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: opencost
    name: <CLUSTER_DESTINATION>
  project: <PROJECT>
  source:
    chart: opencost
    repoURL: https://opencost.github.io/opencost-helm-chart
    targetRevision: 1.29.1
    helm:
      releaseName: opencost
      # values: |
      #   example: value
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
