---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datadog-agent-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  project: <PROJECT>
  source:
    repoURL: <GITOPS_REPO_URL>
    path: <REGISTRY_PATH>/components/datadog-agent
    targetRevision: HEAD
  destination:
    name: <CLUSTER_DESTINATION>
    namespace: datadog-agent
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
