---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kutt
  namespace: argocd
spec:
  project: default
  source:
    chart: kutt
    repoURL: https://christianknell.github.io/helm-charts
    targetRevision: 2.10.4
    helm:
      releaseName: my-release
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kutt
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
