---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: <CLUSTER_NAME>-tetragon
  namespace: argocd
  annotations:
    kubefirst.konstruct.io/application-name: tetragon
    kubefirst.konstruct.io/source: catalog-templates
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: tetragon
    name: <CLUSTER_DESTINATION>
  source:
    repoURL: https://helm.cilium.io/
    targetRevision: 1.2.0  # Update this to the desired version, this is the current lastest (stable) version on the Cilium Helm repository
    chart: tetragon
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
