---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: <CLUSTER_NAME>-stormforge-agent
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '3'
    kubefirst.konstruct.io/application-name: stormforge-agent
    kubefirst.konstruct.io/source: catalog-templates
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: stormforge-system
    name: <CLUSTER_DESTINATION>
  project: <PROJECT>
  source:
    chart: stormforge-agent
    repoURL: registry.stormforge.io/library
    targetRevision: 2.10.8
    helm:
      releaseName: stormforge
      values: |
        clusterName: <CLUSTER_NAME>
        stormforge:
          address: https://api.stormforge.io/
        manageAuthSecret: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
