---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: testkube-secret
  namespace: testkube
spec:
  target:
    name: testkube-api.cloud.key
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv-secret
  refreshInterval: 10s
  dataFrom:
    - extract:
        key: /testkube-api.cloud.key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: testkube-secret
  namespace: testkube
spec:
  target:
    name: testkube-api.cloud.orgId
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv-secret
  refreshInterval: 10s
  dataFrom:
    - extract:
        key: /testkube-api.cloud.orgId
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: testkube-secret
  namespace: testkube
spec:
  target:
    name: testkube-api.cloud.envId
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv-secret
  refreshInterval: 10s
  dataFrom:
    - extract:
        key: /testkube-api.cloud.envId