---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: kratix-git-access
  namespace: kratix-platform-system
spec:
  target:
    name: default-git-secret
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv-secret
  refreshInterval: "10s"
  data:
    - remoteRef:
        key: ci-secrets
        property: BASIC_AUTH_USER
      secretKey: username
    - remoteRef:
        key: ci-secrets
        property: PERSONAL_ACCESS_TOKEN
      secretKey: password
---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: kratix-bucket-access
  namespace: kratix-platform-system
spec:
  target:
    name: default-bucket-secret
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv-secret
  refreshInterval: "10s"
  data:
    - remoteRef:
        key: minio
        property: accesskey
      secretKey: accessKeyID
    - remoteRef:
        key: minio
        property: secretkey
      secretKey: secretAccessKey
