---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: <CLUSTER_NAME>-testkube
  namespace: argocd
  annotations:
    kubefirst.konstruct.io/application-name: testkube
    kubefirst.konstruct.io/source: catalog-templates
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: testkube
    name: <CLUSTER_DESTINATION>
  project: <PROJECT>
  source:
    chart: testkube
    repoURL: https://kubeshop.github.io/helm-charts
    targetRevision: 1.11.214
    helm:
      releaseName: testkube
      values: |
        testkube-api.minio.enabled: false
        mongodb.enabled: false
        testkube-dashboard.enabled: false
        testkube-api.cloud.existingSecret.name: <CLUSTER_NAME>-testkube-secret
        testkube-api.cloud.existingSecret.key: API_KEY
        testkube-api.cloud.existingSecret.orgId: ORG_ID
        testkube-api.cloud.existingSecret.envId: ENV_ID
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
