---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: testkube-<ENVIRONMENT>-secret
  namespace: testkube
spec:
  target:
    name: testkube
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv-secret
  refreshInterval: 10s
  dataFrom:
    - extract:
        key: /testkube
