---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: <CLUSTER_NAME>-kubescape-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '10'
    kubefirst.konstruct.io/application-name: kubescape-operator
    kubefirst.konstruct.io/source: catalog-templates
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: <PROJECT>
  source:
    repoURL: 'https://kubescape.github.io/helm-charts/'
    targetRevision: 1.17.3
    chart: kubescape-operator
    helm:
      values: |
        clusterName: <CLUSTER_NAME>
  destination:
    name: <CLUSTER_DESTINATION>
    namespace: kubescape
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
