---
apiVersion: typesenseproject.org/v1
kind: TypesenseOperator
metadata:
  name: type-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '20'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  replicas: 1
  namespace: typesense
  image: typesense/typesense:0.25.2
  resources:
    requests:
      memory: 100Mi
      cpu: "100m"
    limits:
      memory: 200Mi
      cpu: "100m"
  nodeSelector:
    kubernetes.io/os: linux
config:
  password: "writepassword"
