---
name: Syntax Validation
on: [push, workflow_dispatch]

jobs:
  syntax-check:
    name: vale
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3.5.3

      - name: Install Vale
        run: |
          wget https://github.com/errata-ai/vale/releases/download/v2.30.0/vale_2.30.0_Linux_64-bit.tar.gz -O vale.tar.gz
          tar -xvzf vale.tar.gz vale
          rm vale.tar.gz

      - name: Validate the syntax
        run: ./vale --config=.vale.ini *.md
