---
name: Markdown Links Validation

on: [push, workflow_dispatch]

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout this repository
        uses: actions/checkout@v3.5.3

      - name: Validate Links in Markdown files
        if: always()
        uses: gaurav-nelson/github-action-markdown-link-check@1.0.15
        with:
          config-file: '.markdownlinkcheck.json'
          use-quiet-mode: 'yes'
          file-extension: .md
